export const Const = {
  API_URL: "http://localhost:8080",
  LOGIN: "/login",
  bs_CLIENT: "/bs_client/",
  bs_DOC : "/bs_doc/",
  bs_DOCS_CATEGORY : "/bs_docs_category/",
  bs_EMPLOYEE : "/bs_employee/",
  bs_INVOICE : "/bs_invoice/",
  bs_KB : "/bs_kb/",
  bs_KB_CATEGORY : "/bs_kb_category/",
  bs_MANAGER : "/bs_manager/",
  bs_PRIORITY : "/bs_priority/",
  bs_STATUS : "/bs_status/",
  bs_TASK_CATEGORY : "/bs_task_category/",
  bs_TYPE : "/bs_type/",
  BUSINESS: "/business/",
  bs_pr_CHANNEL : "/bs_pr_channel/",
  bs_pr_COMMENT : "/bs_pr_comment/",
  bs_pr_DOCS : "/bs_pr_docs/",
  bs_pr_DOCS_CATEGORY : "/bs_pr_docs_category/",
  bs_pr_KB : "/bs_pr_kb/",
  bs_pr_KB_CATEGORY : "/bs_pr_kb_category/",
  bs_pr_MENTION : "/bs_pr_mention/",
  bs_PROJECT : "/bs_project/",
  bs_pr_TASK : "/bs_pr_task/",
  ADMIN : "/admin/",
  CLIENT : "/client/",
  EMPLOYEE : "/employee/",
  INVOICE : "/invoice/",
  MAIN_HQ : "/mainHQ/",
  PLAN : "/plan/"
}
