export const userRole = {
  BS_CLIENT : "ROLE_BS_CLIENT",
  BS_EMPLOYEE : "ROLE_BS_EMPLOYEE",
  BS_MANAGER : "ROLE_BS_MANAGER",
  ADMIN : "ROLE_ADMIN",
  CLIENT : "ROLE_CLIENT",
  EMPLOYEE : "ROLE_EMPLOYEE",
  NO_ROLE : "NO_ROLE"
}
